### PR TITLE
Remove queries from validation

### PR DESCRIPTION
**Pull request by albertkol**
## Done

Remove query validation.

### CODE REVIEW

**Review by mtruj013 — APPROVED** [review]
👍🏻

**Comment by nottrobin** [comment]
Was this done purely to fix https://github.com/canonical-web-and-design/ubuntu.com/issues/11857? Do we know why that particular payload was failing validation? Removing validation seems like a pretty extreme response. If the validation was broken, we should fix it. If it doesn't provide a good description of why the validation failed, we should see if we can improve the message. But removing validation entirely seems likely to cause more problems than it fixes if we end up accepting items with invalid data.

**Comment by albertkol** [comment]
@nottrobin @jpmartinspt @mtruj013 

The payload was actually not the problem. But the API was returning an immense number of 422 responses.

After /security/cve got migrated to talk to the API, the extra requests that were calling the cves.json endpoint flooded the database with so many connections that we were getting `pool_size` errors.

`package_name` and `release_codename` are the two query parameters that do database queries in the validation function. 
Ex: `SELECT package_name from package` if not exist return 422.

Due to the database not having available connections I think the API was returning 422 as a result. So we made the decision to remove the validation, as a quick thing, not even sure it can be called a solution, but we did get rid of the 422.

Since then, I did release a PR that optimised the queries cves.json makes, so the database `pool_size` errors greatly decreased. (they still happen during high number of requests spikes we have early in the morning)

I think it's safe to re-enable these validations. As those queries are fast, and were never the problem, just a symptom. I think those validations were nice to have, but even without them, I would not say things are worse. 

Before if you provided a `package name` or a `release codename` that does not exist in the database, we would throw a 422. 
Now we return you 0 results, because cve/usn match the criteria.

**Comment by nottrobin** [comment]
> On read endpoints I would rather not do these sorts of validations and let the API return 0 results.

Yes I think that's fine

> On creates and updates if we are using foreign keys right this should already fail?

Could we check this? But also, I thought the validator here gave quite rich feedback on what exactly failed to validate. I assume foreign key failures are either completely masked to the client by a generic "server error" or something, or are much more obscure to parse?

I do think providing informative feedback for creation errors is pretty important, and I'd like to make sure we are achieving it. Of course if the way we're doing is prohibitively expensive then a compromise may need to be made, but let's find out the parameters first.

Validating inputs matters, and good error messages matter. Could we please confirm what the situation now is following this PR?

**Comment by nottrobin** [comment]
> @albertkol: package_name and release_codename are the two query parameters that do database queries in the validation function.
> Ex: SELECT package_name from package if not exist return 422.
> 
> Due to the database not having available connections I think the API was returning 422 as a result. So we made the decision to remove the validation, as a quick thing, not even sure it can be called a solution, but we did get rid of the 422.

Thanks, this is really great context. This PR makes a lot more sense now, and it sounds like this is, in intent, a really important optimisation. So thanks for doing it.

(Although let's still please confirm what the situation now is with valuation of inserts)

It would be even more fantastic if you could try to provide as much of this sort of context as possible up front in the PR description to shortcut these sorts of explorations 🙂.

**Pull request merged**
